/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/models/Apple.glb 
*/

import { useGLTF } from '@react-three/drei';
import React, { useRef } from 'react';

export function Apple(props) {
  const { nodes, materials } = useGLTF('/models/Apple.glb')
  const appleRef = useRef();

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Apple1-Mesh'].geometry} material={materials.Red} />
      <mesh geometry={nodes['Apple1-Mesh_1'].geometry} material={materials['Mat.7']} />
    </group>
  )
}

useGLTF.preload('/models/Apple.glb')
