/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/models/Carrot.glb 
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'

export function Carrot(props) {
  const { nodes, materials } = useGLTF('/models/Carrot.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.carrot_1.geometry} material={materials.orange} />
      <mesh geometry={nodes.carrot_1_1.geometry} material={materials.green} />
    </group>
  )
}

useGLTF.preload('/models/Carrot.glb')
