/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/models/Chicken Leg.glb 
*/
import { animated } from '@react-spring/three';
import { useGLTF } from '@react-three/drei';
import React from 'react';
import * as THREE from 'three';
import { useFeedAnimation } from '../hooks/useFeedAnimation';

export function Chicken(props) {
  const { nodes, materials } = useGLTF('/models/Chicken Leg.glb');
  const { dispatchActions, playAudioAction, scale, active, setActive } = useFeedAnimation();

  const handleClick = () => {
    setActive(!active)
    setTimeout(() => {
      setActive(false);
    }, 200);

    dispatchActions();
    playAudioAction();
  };

  return (
    <animated.group 
    {...props} 
    dispose={null}
    scale={scale}
    onClick={handleClick}
    >
      <group scale={100}>
        <mesh geometry={nodes.ChickenLeg_1.geometry} material={materials.Beige} />
        <mesh geometry={nodes.ChickenLeg_2.geometry} material={materials.DarkBrown} />
        <mesh 
        geometry={new THREE.CircleGeometry(0.006, 64)} 
        material={new THREE.MeshBasicMaterial({ color: '#ff9900' })} 
        position={[0, 0, 0]} 
      />
      </group>
    </animated.group>
  )
}

useGLTF.preload('/models/Chicken Leg.glb')
