/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/models/Chicken.glb 
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'

export function Chicken(props) {
  const { nodes, materials } = useGLTF('/models/Chicken.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Chicken_Roundcube001_1.geometry} material={materials['795548']} />
      <mesh geometry={nodes.Chicken_Roundcube001_1_1.geometry} material={materials.FFCC88} />
    </group>
  )
}

useGLTF.preload('/models/Chicken.glb')
