/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/models/Flowers.glb 
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'

export function Flowers(props) {
  const { nodes, materials } = useGLTF('/models/Flowers.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.DesertMarigold_mesh.geometry} material={materials.DesertMarigold_mat} />
    </group>
  )
}

useGLTF.preload('/models/Flowers.glb')
