/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/models/Apple Green.glb 
*/
import { animated } from '@react-spring/three';
import { Html, useGLTF } from '@react-three/drei';
import { useRef } from 'react';
import { useFrame } from 'react-three-fiber';
import { useFeedAnimation } from '../hooks/useFeedAnimation';


export function Green({position}) {
  const ref = useRef();
  const { nodes, materials } = useGLTF('/models/Apple Green.glb')
  const { dispatchActions, playAudioAction, scale, active, setActive } = useFeedAnimation();

  useFrame(() => {
    ref.current.rotation.y += 0.01;
  } );

  const handleClick = () => {
    setActive(!active)
    setTimeout(() => {
      setActive(false);
    }, 200);

    dispatchActions();
    playAudioAction();
  };
  
  return (
    <animated.group 
    ref={ref}
    position={position}
    dispose={null}
    scale={scale}
    onClick={handleClick}
    >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Apple_Green_1.geometry} material={materials.PaleGreen} />
        <mesh geometry={nodes.Apple_Green_2.geometry} material={materials.DarkBrown} />
        <mesh geometry={nodes.Apple_Green_3.geometry} material={materials.DarkGreen} />
      <Html>
        
      </Html>
      </group>
    </animated.group>
  )
}

useGLTF.preload('/models/Apple Green.glb')
