/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/models/Apple Green.glb 
*/
import { animated } from '@react-spring/three';
import { useGLTF } from '@react-three/drei';
import React from 'react';
import { useFeedAnimation } from '../hooks/useFeedAnimation';

export function Green(props) {
  const { nodes, materials } = useGLTF('/models/Apple Green.glb')
  const { dispatchActions, playAudioAction, scale, active, setActive } = useFeedAnimation();

  const handleClick = () => {
    setActive(!active)
    setTimeout(() => {
      setActive(false);
    }, 200);

    dispatchActions();
    playAudioAction();
  };
  
  return (
    <animated.group 
    {...props} 
    dispose={null}
    scale={scale}
    onClick={handleClick}
    >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Apple_Green_1.geometry} material={materials.PaleGreen} />
        <mesh geometry={nodes.Apple_Green_2.geometry} material={materials.DarkBrown} />
        <mesh geometry={nodes.Apple_Green_3.geometry} material={materials.DarkGreen} />
      </group>
    </animated.group>
  )
}

useGLTF.preload('/models/Apple Green.glb')
