/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/models/Lettuce.glb 
*/
import { animated } from '@react-spring/three';
import { useGLTF } from '@react-three/drei';
import React from 'react';
import { useFeedAnimation } from '../hooks/useFeedAnimation';

export function Lettuce(props) {
  const { nodes, materials } = useGLTF('/models/Lettuce.glb');
  const { dispatchActions, playAudioAction, scale, active, setActive } = useFeedAnimation();

  const handleClick = () => {
    setActive(!active)
    setTimeout(() => {
      setActive(false);
    }, 200);

    dispatchActions();
    playAudioAction();
  };

  return (
    <animated.group 
    {...props} 
    dispose={null}
    scale={scale}
    onClick={handleClick}
    >
      <mesh geometry={nodes.Lettuce_Whole.geometry} material={materials.PaleGreen} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </animated.group>
  )
}

useGLTF.preload('/models/Lettuce.glb')
