/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/models/Lettuce.glb 
*/
import { animated } from '@react-spring/three';
import { useGLTF } from '@react-three/drei';
import { useRef } from 'react';
import { useFrame } from 'react-three-fiber';
import { useFeedAnimation } from '../hooks/useFeedAnimation';

export function Lettuce({position}) {
  const ref = useRef();
  const { nodes, materials } = useGLTF('/models/Lettuce.glb');
  const { dispatchActions, playAudioAction, scale, active, setActive } = useFeedAnimation();

  useFrame(() => {
    ref.current.rotation.y += 0.01;
  });

  const handleClick = () => {
    setActive(!active)
    setTimeout(() => {
      setActive(false);
    }, 200);

    dispatchActions();
    playAudioAction();
  };

  return (
    <animated.group 
    ref={ref}
    position={position}
    scale={scale}
    onClick={handleClick}
    >
      <mesh geometry={nodes.Lettuce_Whole.geometry} material={materials.PaleGreen} rotation={[-Math.PI / 2, 0, 0]} scale={75} />
    </animated.group>
  )
}

useGLTF.preload('/models/Lettuce.glb')
