/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/Mountain.glb 
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'

export function Mountain(props) {
  const { nodes, materials } = useGLTF('models/Mountain.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Mountain_Cube-Mesh'].geometry} material={materials['455A64']} />
      <mesh geometry={nodes['Mountain_Cube-Mesh_1'].geometry} material={materials.FFFFFF} />
      <mesh geometry={nodes['Mountain_Cube-Mesh_2'].geometry} material={materials['8BC34A']} />
    </group>
  )
}

useGLTF.preload('models/Mountain.glb')
