/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/Tree.glb 
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'

export function Tree(props) {
  const { nodes, materials } = useGLTF('/models/Tree.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} scale={46.324} />
      <mesh geometry={nodes.Icosphere003.geometry} material={materials['Material.001']} position={[0.405, 6.347, -0.703]} rotation={[-Math.PI / 2, 0, 0]} scale={139.01} />
    </group>
  )
}

useGLTF.preload('/models/Tree.glb')
