/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/models/Tree.glb 
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'

export function Tree(props) {
  const { nodes, materials } = useGLTF('/models/Tree.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={51.843}>
        <mesh geometry={nodes.Tree_3_1.geometry} material={materials.Tree_Green} />
        <mesh geometry={nodes.Tree_3_2.geometry} material={materials.Tree_Wood} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Tree.glb')
